version: "3"

services:
  app:
    container_name: ds_dev_app
    image: isarbits/docuvision-studio-app
    build:
      context: ../app
    restart: always
    env_file: ../app/server/.env.example
    environment:
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
      - DOCUVISION_HOST=${DOCUVISION_HOST}
      - EXTERNAL_WORKERS=true
      - OCR_ENGINE=${OCR_ENGINE}
    network_mode: host
    ports:
      - "8100:8100"
    depends_on:
      - es
      - redis
    volumes:
      - "${GENERATED_DIR}:/opt/dist/static"

      - ../app/server/dist:/opt/dist
      - ../app/client/build:/client/build
    # command: pm2-runtime /opt/pm2/pm2-config-watch.json
    command: pm2-runtime /opt/pm2/pm2-config-watch.json --only server

  workers:
    container_name: ds_dev_workers
    image: isarbits/docuvision-studio-app
    build:
      context: ../app
    restart: always
    env_file: ../app/server/.env.example
    environment:
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
      - DOCUVISION_HOST=${DOCUVISION_HOST}
      - WORKERS_CLUSER_AUTO_SCALE=true
      - WORKERS_CLUSER_MAX=10
      - OCR_ENGINE=${OCR_ENGINE}
    network_mode: host
    depends_on:
      - es
      - redis
    volumes:
      - ./worker-static:/opt/dist/static
      - ../app/server/dist:/opt/dist
    command: pm2-runtime /opt/pm2/pm2-config-watch.json --only workers

  indexer:
    container_name: ds_dev_indexer
    image: isarbits/docuvision-studio-indexer
    build:
      context: ../indexer-cli
    restart: always
    network_mode: host
    environment:
      - ELASTICSEARCH_NODE=http://localhost:9200
      - DOCUVISION_HOST=${DOCUVISION_HOST}
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
      - OCR_ENGINE=tesseract
      - ISWIN=${WINDIR}
    volumes:
      - "${INPUT_DIR}:/data"
      - "${GENERATED_DIR}:/generated-files"

      - ../indexer-cli/dist:/opt/dist
    command: npx nodemon --exec 'node ./src/index.js index --watch /data'

  es:
    container_name: ds_elastic
    image: isarbits/es-kibana
    volumes:
      - ./elasticdata:/home/elasticsearch/elasticsearch/data
    ports:
      - "9200:9200" # elastic
      - "5601:5601" # kibana

  redis:
    container_name: ds_redis
    image: redis:alpine
    ports:
      - 6379:6379
