version: "3"

services:
  es:
    container_name: ds_elastic
    image: isarbits/es-kibana
    volumes:
      - esdata:/home/elasticsearch/elasticsearch/data
    ports:
      - "9200:9200" # elastic
      - "5601:5601" # kibana

  app:
    container_name: ds_app
    image: isarbits/docuvision-studio-app
    restart: always
    environment:
      - PORT=8100
      - ELASTICSEARCH_NODE=http://ds_elastic:9200
      - NODE_ENV=production
    ports:
      - "8100:8100"
    volumes:
      - "${GENERATED_DIR}:/opt/dist/app/generated-files"

  indexer:
    container_name: ds_indexer
    image: isarbits/docuvision-studio-indexer
    restart: always
    network_mode: host
    environment:
      - ELASTICSEARCH_NODE=http://localhost:9200
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
    volumes:
      - "${INPUT_DIR}:/data"
      - "${GENERATED_DIR}:/generated-files"

volumes:
  esdata:
