version: "3"

services:
  es:
    container_name: ds_elastic
    image: isarbits/es-kibana
    volumes:
      - esdata:/home/elasticsearch/elasticsearch/data
    ports:
      - "9200:9200" # elastic
      - "5601:5601" # kibana

  client:
    container_name: ds_client
    build:
      context: ../client
    image: isarbits/ds-client
    restart: always
    environment:
      - BROWSER=none
      - PORT=8100
    ports:
      - "8100:8100"
    volumes:
      - ../client/public:/opt/public
      - ../client/src:/opt/src

  indexer:
    container_name: ds_indexer
    build:
      context: ../node-cli
    image: isarbits/ds-indexer
    restart: always
    network_mode: host
    environment:
      - ELASTICSEARCH_NODE=http://localhost:9200
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
    volumes:
      - ${DATA_DIR}:/data
      - ../node-cli/dist:/opt/dist

volumes:
  esdata:
