version: "3"

services:
  es:
    container_name: ds_elastic
    image: isarbits/es-kibana
    volumes:
      - esdata:/home/elasticsearch/elasticsearch/data
    ports:
      - "9200:9200" # elastic
      - "5601:5601" # kibana

  app:
    container_name: ds_dev_app
    image: isarbits/docuvision-studio-app
    build:
      context: ../app
    restart: always
    environment:
      - PORT=8100
      - ELASTICSEARCH_NODE=http://ds_elastic:9200
      - NODE_ENV=development
    ports:
      - "8100:8100"
    volumes:
      - "${GENERATED_DIR}:/opt/dist/static/public"

      - ../app/server/dist:/opt/dist
      - ../app/client/build:/client/build
    command: npx nodemon --watch dist --exec 'cd dist && node src/main.js'

  indexer:
    container_name: ds_dev_indexer
    image: isarbits/docuvision-studio-indexer
    build:
      context: ../indexer-cli
    restart: always
    network_mode: host
    environment:
      - ELASTICSEARCH_NODE=http://localhost:9200
      - DOCUVISION_HOST=${DOCUVISION_HOST}
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
      - ISWIN=${WINDIR}
    volumes:
      - "${INPUT_DIR}:/data"
      - "${GENERATED_DIR}:/generated-files"

      - ../indexer-cli/dist:/opt/dist
    command: npx nodemon --exec 'node ./src/index.js index --watch /data'

volumes:
  esdata:
