version: "3"

services:
  es:
    container_name: ds_elastic
    image: isarbits/es-kibana
    volumes:
      - ./elasticdata:/home/elasticsearch/elasticsearch/data
    ports:
      - "9200:9200" # elastic
      - "5601:5601" # kibana

  app:
    container_name: ds_app
    image: isarbits/docuvision-studio-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8100
      - DOCUVISION_APIKEY=${DOCUVISION_APIKEY}
    network_mode: host
    ports:
      - "8100:8100"
    volumes:
      - "${GENERATED_DIR}:/opt/dist/static/public"

  indexer:
    container_name: ds_indexer
    image: isarbits/docuvision-studio-indexer
    restart: always
    network_mode: host
    environment:
      - NODE_ENV=production
      # - ELASTICSEARCH_INDEX_WORDS=true
      - ISWIN=${WINDIR}
    volumes:
      - "${INPUT_DIR}:/data"
      - "${GENERATED_DIR}:/generated-files"

  redis:
    container_name: ds_redis
    image: redis:alpine
    ports:
      - 6379:6379
